export const ROUTES = {
  HOME: "/",
  DASHBOARD: "/dashboard",
  FLIGHTS: "/flights",
  FLIGHT_DETAIL: "/flights/:id",
  FLIGHT_PLAN: "/flights/plan",
  AIRSPACE: "/airspace",
  CONSTRAINTS: "/airspace/constraints",
  OPERATIONAL_INTENTS: "/airspace/operational-intents",
  PROVIDERS: "/providers",
  PROVIDER_DETAIL: "/providers/:id",
  NOTIFICATIONS: "/notifications",
  REPORTS: "/reports",
  REPORT_DETAIL: "/reports/:id",
  LOGIN: "/auth/login",
  PROFILE: "/auth/profile",
  SETTINGS: "/settings",
  ADMIN: "/admin",
  NOT_FOUND: "*",
} as const;